version: '3'
services:
  zookeeper:
    platform: linux/x86_64
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.9.2-debian-12-r7'
    user: root
    ports:
      - "2181:2181"
    volumes:
      - './build/docker-volumes/zookeeper_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: 'no'
    networks:
      - kafka-basics

  kafka:
    platform: linux/x86_64
    image: 'docker.io/bitnami/kafka:3.3.2-debian-12-r26'
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - './build/docker-volumes/kafka_data:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    restart: 'no'
    networks:
      - kafka-basics
  control-center:
      image: confluentinc/cp-enterprise-control-center:latest
      hostname: control-center
      container_name: control-center
      depends_on:
        - kafka
      ports:
        - "9021:9021"
      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
        CONTROL_CENTER_REPLICATION_FACTOR: 1
        PORT: 9021
      networks:
        - kafka-basics

networks:
  kafka-basics:
    driver: bridge
